"""create_all_tables

Revision ID: 0e5cdd637cf0
Revises: 
Create Date: 2026-01-17 19:09:36.738005

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0e5cdd637cf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    op.create_index(op.f('ix_certificates_code'), 'certificates', ['code'], unique=True)
    op.create_index(op.f('ix_certificates_name'), 'certificates', ['name'], unique=False)
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cohort_id'),
    sa.UniqueConstraint('year_start')
    )
    op.create_table('majors',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('major_id')
    )
    op.create_index(op.f('ix_majors_name'), 'majors', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('semesters',
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('semester_id')
    )
    op.create_index(op.f('ix_semesters_name'), 'semesters', ['name'], unique=True)
    op.create_table('subjects',
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=True)
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    op.create_table('graduation_criteria',
    sa.Column('graduation_criteria_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('default_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.PrimaryKeyConstraint('graduation_criteria_id')
    )
    op.create_index(op.f('ix_graduation_criteria_name'), 'graduation_criteria', ['name'], unique=False)
    op.create_table('training_programs',
    sa.Column('training_program_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.PrimaryKeyConstraint('training_program_id')
    )
    op.create_index(op.f('ix_training_programs_name'), 'training_programs', ['name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('criteria_certificates',
    sa.Column('criteria_certificate_id', sa.Integer(), nullable=False),
    sa.Column('graduation_criteria_id', sa.Integer(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.certificate_id'], ),
    sa.ForeignKeyConstraint(['graduation_criteria_id'], ['graduation_criteria.graduation_criteria_id'], ),
    sa.PrimaryKeyConstraint('criteria_certificate_id')
    )
    op.create_table('criteria_subjects',
    sa.Column('criteria_subject_id', sa.Integer(), nullable=False),
    sa.Column('graduation_criteria_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['graduation_criteria_id'], ['graduation_criteria.graduation_criteria_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('criteria_subject_id')
    )
    op.create_table('program_certificates',
    sa.Column('program_certificate_id', sa.Integer(), nullable=False),
    sa.Column('training_program_id', sa.Integer(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.certificate_id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.training_program_id'], ),
    sa.PrimaryKeyConstraint('program_certificate_id')
    )
    op.create_table('program_subjects',
    sa.Column('program_subject_id', sa.Integer(), nullable=False),
    sa.Column('training_program_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['training_program_id'], ['training_programs.training_program_id'], ),
    sa.PrimaryKeyConstraint('program_subject_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.major_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.certificate_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_table('scores',
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('score_4', sa.Float(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=False),
    sa.Column('score_10', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_table('students')
    op.drop_table('program_subjects')
    op.drop_table('program_certificates')
    op.drop_table('criteria_subjects')
    op.drop_table('criteria_certificates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_programs_name'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_graduation_criteria_name'), table_name='graduation_criteria')
    op.drop_table('graduation_criteria')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_semesters_name'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_majors_name'), table_name='majors')
    op.drop_table('majors')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_certificates_name'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_code'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
