"""fix_notification_user_relation

Revision ID: a656e3ca1e0f
Revises: e24d59640ef4
Create Date: 2025-12-21 00:01:36.420592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a656e3ca1e0f'
down_revision = 'e24d59640ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'users', ['user_id'], ['user_id'])
    op.drop_column('notification', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###
