"""init_fsi_academic_system

Revision ID: e24d59640ef4
Revises: 
Create Date: 2025-12-20 23:43:10.987721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e24d59640ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('kdb', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tdc', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sum_tc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('intake_id')
    )
    op.create_table('major',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('major_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('major_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tcdh', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_bb', sa.Boolean(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.intake_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.major_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intake.intake_id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.major_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('score',
    sa.Column('id_score', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id_score')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('student')
    op.drop_table('upload_history')
    op.drop_table('class')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('course')
    op.drop_table('roles')
    op.drop_table('notification')
    op.drop_table('major')
    op.drop_table('intake')
    # ### end Alembic commands ###
